# Introduction

R code run_analysis.R performs the 5 steps:

* All data is merged using the rbind() function. Create three data sets: x(test+train), y(test+train), s(test+train). 
* Only those columns with the mean and standard deviation measures are taken from the whole dataset. After extracting these columns, they are given the correct names, taken from features.txt.
* Take the activity names and IDs from activity_labels.txt and they are substituted in the dataset.
* On the whole dataset, those columns with vague column names are corrected.
* Finally, we generate a new dataset with all the average measures for each subject and activity type (30 subjects * 6 activities = 180 rows). The output file is called final_data.txt, and uploaded to this repository.


# Variables
* x_trn, y_trn, x_tst, y_tst, s_trn and s_tst contain the data from the downloaded files.
* data_x, data_y and data_s merge the previous datasets.
* features contains names for the data_x dataset, which are applied to the 
* column names stored in mean_std
* A similar approach is taken with activity names through the activities variable.
* "merged" merges together data_x, data_y and data_s.
* final_data contains averages which will be later stored in a .txt file. ddply() from the plyr package is used to apply colMeans() and ease the development.